<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>VideoPlayer</RootNamespace>
    <AssemblyName>VideoPlayer</AssemblyName>
    <ApplicationIcon>VideoPlayer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="VideoPlayer.ico"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.5" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
  </ItemGroup>

</Project>
