<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>VideoPlayer</RootNamespace>
    <AssemblyName>VideoPlayer</AssemblyName>
    <ApplicationIcon>VideoPlayer.ico</ApplicationIcon>
    <Version>0.2.8</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="VideoPlayer.ico"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="FFmpeg\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FlyleafLib" Version="3.10.2" />
    <PackageReference Include="FlyleafLib.Controls.WPF" Version="1.6.2" />
    <PackageReference Include="Flyleaf.FFmpeg.Bindings" Version="8.0.1" />
  </ItemGroup>

</Project>
